### ISSUE TITLE
Thoughts on making this an official community plugin?

### ISSUE THREAD

**Issue by majormoses** [mattronix/handler-mattermost#1]
I am a maintainer of https://github.com/sensu-plugins and was wondering if you might be interested in making this an official community plugin? The process for transfer is outlined here: https://github.com/sensu-plugins/community/blob/master/TRANSFERRING_REPOS.md. Aside from you transfering it over there is no real effort on your end as I will do all the standard stuff for plugins for you.

**Comment by mattronix** [comment]
Sure would love to will look at the process tomorrow :)

**Comment by majormoses** [comment]
Just a friendly ping reminder now that it is a new year.

**Comment by mattronix** [comment]
hi i have filled in the template :)

**Comment by mattronix** [comment]
I would love to transfer the repo can someone give me the official repo to transfer to :)?

**Comment by majormoses** [comment]
Sorry missed the comment, I can't "give you a repo" you need to initiate a transfer to me and I can transfer it to the org. I have linked you to documentation for this already.

**Comment by majormoses** [comment]
It's now under the community org, will open an issue to track the basic stuff.

**Comment by majormoses** [comment]
see #3
